"""Defines the items generated by the spider after check a website's link

This file can be imported as a module and contains the following classes:
    * MonitorItem - Defines the website metrics collected by the Spider
"""

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class MonitorItem(scrapy.Item):  # pylint: disable=too-many-ancestors
    """Defines the websites metrics collected by the Spider

    Attributes
    ----------
    url : scrapy.Field()
        Website's url
    error_code : scrapy.Field()
        Error code as a result of try to get a resource from internet. Could
        include 200
    response_time : scrapy.Field()
        Time lapsed while waiting for a response
    regex_pattern : scrapy.Field()
        Regex pattern to look for in the result HTML page
    matched_text : scrapy.Field()
        Text in the result HTML page that match the specified regex_pattern
    """

    url = scrapy.Field()
    error_code = scrapy.Field()
    response_time = scrapy.Field()
    regex_pattern = scrapy.Field()
    matched_text = scrapy.Field()
